spring.application.name=proxymaze
server.port=8080
spring.jackson.default-property-inclusion=always
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.deserialization.fail_on_unknown_properties=false
